server:
  port: 8083
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: polizas
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/catshout
    username: postgres
    password: admin